name: go-test

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feature/use_modules
      - uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version-file: "go.mod"

      - name: Test
        run: go test -v ./...
